### PR TITLE
a googol of reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee…

### PR DESCRIPTION
**Pull request by xenomancer**
Writes reee followed by 10¹⁰⁰ replicates of "eee". Do not load it into an xml parser.

How could you store this, you ask? Well... Let's first assume that the parser has zero overhead and exists as a purely abstract object in spacetime but is capable of storing information to modern storage hardware automagically with no other device interactions needed. Let us then assume that the data is stored at an astounding 100% efficiency as full 8 bit ASCII text, because somehow alignment still matters or whatever fuck you this is napkin math time. [This article](https://www.zdnet.com/article/intel-this-ruler-ssd-is-worlds-densest-so-you-can-cram-1pb-in-single-1u-rack/) claims that some supercalifragilistic Intel ssd can hold 32TB in a device. Some fiddling about the [Intel site](https://ark.intel.com/products/series/96935/Intel-SSD-DC-P4500-Series) and the quoted 12 x 1.5 x 0.33 in³ volume from the article is matched by a mass of 225g.

**prepare your optical orifices for the impressive numbers**

So, 35,184,372,088,832 bytes, which are 1-to-1 equivalent with stored characters, need only 225g (0.225Kg) of mass and ~100mL (0.0001m³) of volume. The first question to answer is how many bytes are being stored? If you add them all up, the number is still small enough to write if you can get through the laughter (stop that! stop that now. this is science and science is serious):

1,055,531,162,664,960,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,003 bytes

How many SSDs would be required to hold this? 

9,094,947,017,729,282,379,150,390,625,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000 SSDs

How much mass would be required?

2,046,363,078,989,088,535,308,837,890,625,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000 Kg

or

~342,659,591,257,382,541,076,496,632,723,540,000,000,000,000,000,000,000,000,000,000 Earth masses

How much space would this take up is gravity was also magically of no concern?

90,949,470,177,292,823,791,503,906,250,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000 m³

or

~82,868,959,382,395,162,676,499,753,532,885,000,000,000,000,000,000,000,000,000,000,000,000 Earth volumes

But... what if we did consider gravity? The Schwarzschild radius is fairly impressive.

~3,039,223,855,692,262,229,797,054,404,722,800,000,000,000,000,000,000,000,000,000 m

or

~321,246,215,025,422,872,876,690,572,752.64 ly

And the radius of a hypothetical sphere of SSDs required to get the job done is

~278,978,362,874,806,659,664,010,712,316.81 m

or

~29,488,036,223,349.245862068299531208 ly

Which means that provided the ridiculous assumptions from before, it wouldn't matter because that amount of mass would instantly form a black  hole and everyone that cared about seeing the last e would never be able to communicate their joy to the rest of the universe. Of course, given the amount of time requirement assumed for such a device to complete the computation, no one would be alive to communicate by the time the job was completed.

That is correct. The minimum hardware requirements to store the output from parsing this file would near instantly kill everyone and everything and nobody would be alive to hear about the last e if they escaped.

I think that this satisfactorily meets the spirit of this project.

### CODE REVIEW

**Comment by xenomancer** [comment]
I am not sure if such a device could run Crysis...

**Comment by ScottMansfield** [comment]
<reee>&reeee;&reee100;</reee>

**Comment by xenomancer** [comment]
For ref: http://allguids.cdmansfield.com/

**Comment by shreyasminocha** [comment]
Could you create a [yaml version](https://en.wikipedia.org/wiki/Billion_laughs_attack#Variations) too?

**Pull request merged**
