### PR TITLE
Create reee.css

### PR DESCRIPTION
**Pull request by farazkaleemmalik**
reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

### CODE REVIEW

**Comment by arch-lord** [comment]
Use of `content` would be better imo.

**Comment by farazkaleemmalik** [comment]
Fair enough

**Comment by markski1** [comment]
This doesn't look like it would print an R, and then indefinitely print an E as standarized.

**Comment by farazkaleemmalik** [comment]
True, I was not aware of these strict guidelines.

**Pull request closed without merging**
